## **Report**: Scientology Grand Openings, 2003 - 2026

###### **Date**: June 28, 2026

###### **Analysis & Story Description**: This notebook contains data scraped from the Church of Scientology's grand openings webpage, which documents the properties they have chosen to formally celebrate between 2003 - 2026. I used this data to examine the geographic concentration and growth patterns of the organization as reflected by these highlighted establishments.

### **Step 1:** Import necessary libraries (beautiful soup & pandas) to scrape the webpage for location names, article titles and opening dates.

In [155]:
import requests 
from bs4 import BeautifulSoup #assists with parsing HTML for scraping. 
import pandas as pd #generates and manages dataframes (dfs).

### **Step 2:** Make a cell for the grand opening's webpage URL and send requests

In [156]:
url = 'https://www.scientologynews.org/press-releases/church-openings/'
response = requests.get(url) #sends request to website to download the web info
doc = BeautifulSoup(response.text, 'html.parser') #takes HTML from web from downloaded webpage/website

In [157]:
response.status_code

200

In [158]:
doc #let's you see all that you're working with.

<!DOCTYPE html>

<!--[if lte IE 6]><html class="ie6 ie67 ie678" lang="en"><![endif]-->
<!--[if lte IE 7]><html class="ie7 ie67 ie678" lang="en"><![endif]-->
<!--[if IE 8]><html class="ie8 ie678" lang="en"><![endif]-->
<!--[if gt IE 8]><!--><html itemscope="" itemtype="http://schema.org/WebPage" lang="en"><!--<![endif]-->
<head>
<!-- Sun, 28 Jun 2026 12:04:36 PDT -->
<meta charset="utf-8"/>
<meta content="yes" name="apple-mobile-web-app-capable"/>
<meta content="black-translucent" name="apple-mobile-web-app-status-bar-style"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<meta content="NOODP,NOYDIR" name="robots"/>
<meta content="en" property="og:locale"/>
<script type="application/ld+json">
	{
	  "@context": "http://schema.org",
	  "@type": "WebSite",
	  "url": "http://www.scientologynews.org/",
	  "potentialAction": [{
	    "@type": "SearchAction",
	    "target": "http://www.scientologynews.org/search.html?q={search_term_string}",
	    "query-input": "required name=search_term_string"
	  },{
	    "@type": "SearchAction",
	    "target": "android-app://org.scientologynews/http://www.scientologynews.org/search.html?q={search_term_string}",
	    "query-input": "required name=search_term_string"
	  }]
	}
	</script>
<link href="https://fonts.googleapis.com/css2?family=Jost:ital,wght@0,300;0,400;0,500;1,300;1,400;1,500&amp;display=swap" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital@0;1&amp;display=swap" rel="stylesheet"/>
<title>New Churches of Scientology Grand Openings - PRESS RELEASES</title>
<meta content="Press Releases from the Church of Scientology International regarding opening of new Scientology Churches." name="description"/>
<meta content="https://www.scientologynews.org/press-releases/church-openings/" property="og:url">
<meta content="Scientology News" property="og:site_name">
<meta content="article" property="og:type">
<meta content="" property="og:title">
<meta content="Press Releases from the Church of Scientology International regarding opening of new Scientology Churches." property="og:description">
<meta content="https://files.scientology.org/data/www.scientologynews.org/files/news/images/scientology-newsroom-og-image_en.jpg?k=hfrV_PEiFw" property="og:image">
<meta content="1200" property="og:image:width">
<meta content="630" property="og:image:height"/>
<meta content="summary_large_image" name="twitter:card"/>
<meta content="@scientology" name="twitter:site"/>
<meta content="" name="twitter:title"/>
<meta content="Press Releases from the Church of Scientology International regarding opening of new Scientology Churches." name="twitter:description"/>
<meta content="569385363168364" property="fb:app_id"/>
<meta content="633862040" property="fb:admins"/>
<link href="/theme/css/_combined_bs.css?_=sRdehd0h" rel="stylesheet" type="text/css"/>
<link href="/theme/css/banner-external.css?_=sRdehd0h" rel="stylesheet"/>
<link href="/theme/css/listings.css" rel="stylesheet"/>
<style>

.left-sidebar-listing h2 {
	font-size: 21px;
	font-weight: 400;
}

.left-sidebar-listing h3 {
	font-size: 18px;
	font-weight: 300;
	margin-bottom: 10px
}

.left-sidebar-listing h3 a:active,
.left-sidebar-listing h3 a:hover,
.left-sidebar-listing h3 a {
	color: #326188;
}

.left-sidebar-listing img {
	max-width: 100%;
}

.left-sidebar-listing .small-left-img {
	max-width: 100px;
	margin-right: 17px;
	float: left;
}

.left-sidebar-listing {
	font-size: 14px;
	font-weight: 300;
	line-height: 1.4;
	font-family: "Jost", Arial, Verdana, sans;
}

.left-sidebar-listing .item {
	margin-bottom: 20px;
	display: block;
	color: #555;
}

@media (min-width: 768px) {
	#sidebar_left {
	    width: 29.16666667%;
	}
}

.left-sidebar-listing section {
	padding: 0 0 0 10px;
}

.left-sidebar-listing articles {
	padding: 10px  0 0 20px;
	display: none;
}

.left-sidebar-listing h3 a.disabled {
	pointer-events: none;
	color: #AAABB3;
}

.article .inline-img-block-30 img {
	margin-bottom: 15px;
}

@media (max-width: 767px) {
	.article .inline-img-block-30 img {
		margin-left: auto;
		margin-right: auto;
	}
}

</style>
<link href="/theme/css/banner-external.css?_=sRdehd0h" rel="stylesheet"/>
<script>

	var _gcui_env = 'livesite';
	var globaldata_domain = 'gd.ondemandhosting.info';
	var globaldata_domain2 = 'gd.ondemandhosting.info';
	var globalLang = "en";
	var _gcui_file_url = 'https:\/\/files.ondemandhosting.info';
	var _gcui_sd_url = '//sd.ondemandhosting.info';
	var cacheId = 'sRdehd0h';


	var _gcui_loglevel = 'fatal';


	var _gcui_otherText = 'Other';
	var _gcui_selectElem = '<option value="">Select…</option>';
	var _gcui_otherSpecifyText = 'Other (Specify)';
	var _gcui_campaignName = 'Scientology';
	var _gcui_requiredText = 'gcui_dynaform:field_needs_to_be';


	var _tr = _tr || [];
	</script>
</meta></meta></meta></meta></meta></meta></meta></head>
<body class="context-livesite locale-en path-press-releases path-press-releases-church-openings">
<!--[if lte IE 7]>
<style>
#old_browser { width: 100%; font-size: 13px; background: #f1eca4; height: 35px; font-family: Arial, Verdana, sans-serif; margin: 0; box-sizing: content-box; }
#old_browser .warn { color: #e85c17; font-size: 25px; padding: 0 15px; width: 60px}
#old_browser .msg { padding-right: 10px; }
#old_browser .link { text-align: right; padding-right: 10px; }
#old_browser .link a { color: #e85c17; }
#old_browser .msg-ie { display: none; }
</style>

<table id="old_browser" border="0" cellpadding="0" cellspacing="0">
    <tr>
        <td class="warn"><img width="27" height="22" src="/theme/images/ie-warning-symbol.gif"/></td>
        <td class="msg">Your browser <span class="msg-ie msg-ie6">(Internet Explorer 6)</span> <span class="msg-ie msg-ie7">(Internet Explorer 7)</span> is out of date. It has known security flaws and may not display all features of this and other websites.
        </td>
        <td class="link"><a target="_blank" href="http://browser-update.org/update-browser.html">Learn how to update your&nbsp;browser&nbsp;»</a></td>
    </tr>
</table>
<![endif]-->
<!--[if IE 6]>
<style>
#old_browser .msg-ie.msg-ie6 { display: inline; }
</style>
<![endif]-->
<!--[if IE 7]>
<style>
#old_browser .msg-ie.msg-ie7 { display: inline; }
</style>
<![endif]-->
<!-- external_nav.html -->
<div class="external" id="external">
<div class="container">
<nav class="external-links">
<ul>
<li>
<a href="http://www.lronhubbard.org/"><span>L Ron Hubbard.org</span>
<svg class="svg-arrow arrow-svg-right" height="12" preserveaspectratio="xMidYMid" viewbox="0 0 18 19" width="12" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><path class="cls" d="M18.006,18.997 C18.006,18.997 8.261,9.500 8.261,9.500 C8.261,9.500 18.006,0.003 18.006,0.003 C18.006,0.003 9.740,0.003 9.740,0.003 C9.740,0.003 -0.006,9.500 -0.006,9.500 C-0.006,9.500 9.740,18.997 9.740,18.997 C9.740,18.997 18.006,18.997 18.006,18.997 Z" fill-rule="evenodd" id="path-arrow"></path></svg>
</a>
</li>
<li>
<a href="http://www.scientologyreligion.org/"><span>ScientologyReligion.org</span>
<svg class="svg-arrow arrow-svg-right" height="12" preserveaspectratio="xMidYMid" viewbox="0 0 18 19" width="12" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><path class="cls" d="M18.006,18.997 C18.006,18.997 8.261,9.500 8.261,9.500 C8.261,9.500 18.006,0.003 18.006,0.003 C18.006,0.003 9.740,0.003 9.740,0.003 C9.740,0.003 -0.006,9.500 -0.006,9.500 C-0.006,9.500 9.740,18.997 9.740,18.997 C9.740,18.997 18.006,18.997 18.006,18.997 Z" fill-rule="evenodd" id="path-arrow"></path></svg>
</a>
</li>
<li>
<a href="http://www.freedommag.org/"><span>Freedom Mag.org</span>
<svg class="svg-arrow arrow-svg-right" height="12" preserveaspectratio="xMidYMid" viewbox="0 0 18 19" width="12" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><path class="cls" d="M18.006,18.997 C18.006,18.997 8.261,9.500 8.261,9.500 C8.261,9.500 18.006,0.003 18.006,0.003 C18.006,0.003 9.740,0.003 9.740,0.003 C9.740,0.003 -0.006,9.500 -0.006,9.500 C-0.006,9.500 9.740,18.997 9.740,18.997 C9.740,18.997 18.006,18.997 18.006,18.997 Z" fill-rule="evenodd" id="path-arrow"></path></svg>
</a>
</li>
<li>
<a href="http://www.scientology.org/"><span>Scientology.org</span>
<svg class="svg-arrow arrow-svg-right" height="12" preserveaspectratio="xMidYMid" viewbox="0 0 18 19" width="12" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><path class="cls" d="M18.006,18.997 C18.006,18.997 8.261,9.500 8.261,9.500 C8.261,9.500 18.006,0.003 18.006,0.003 C18.006,0.003 9.740,0.003 9.740,0.003 C9.740,0.003 -0.006,9.500 -0.006,9.500 C-0.006,9.500 9.740,18.997 9.740,18.997 C9.740,18.997 18.006,18.997 18.006,18.997 Z" fill-rule="evenodd" id="path-arrow"></path></svg>
</a>
</li>
</ul>
</nav>
<nav class="external-language-selector" style="display: none">
<div>
<a class="selector"><span>en</span> Language <span>
<svg class="svg-arrow arrow-svg-right" height="12" preserveaspectratio="xMidYMid" viewbox="0 0 18 19" width="12" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><path class="cls" d="M18.006,18.997 C18.006,18.997 8.261,9.500 8.261,9.500 C8.261,9.500 18.006,0.003 18.006,0.003 C18.006,0.003 9.740,0.003 9.740,0.003 C9.740,0.003 -0.006,9.500 -0.006,9.500 C-0.006,9.500 9.740,18.997 9.740,18.997 C9.740,18.997 18.006,18.997 18.006,18.997 Z" fill-rule="evenodd" id="path-arrow"></path></svg>
</span></a>
</div>
<ul>
</ul>
</nav>
</div>
</div>
<!-- /external_nav.html -->
<div id="outer_shell">
<div id="shell">
<div class="container" id="banner" style="padding-left: 40px; padding-right: 0;">
<div class="row" id="banner_inner_table">
<div class="col" id="banner_logo" itemscope="" itemtype="http://schema.org/Brand">
<style>

#shell #banner_logo {
    width: 576px;
}

#header_and_content_container {
    position: relative;
}

#banner_inner_table {
    table-layout: auto;
}

#banner_logo img.light-logo {
    top: 3px;
    left: 3px;
}

@media (max-width: 767px) {



    #outer_shell #shell .logo-holder {
        width: 100%;
        height: 0;
        padding-bottom: 10%;
    }
     #outer_shell #shell #banner {
        overflow: visible;
        height: auto !important;
    }
    #outer_shell #shell #banner_logo {

        padding-top: 2%;
        height: auto;
        position: relative;
        padding-bottom: 0;
    }
    #content {
        background: rgba(255, 255, 255, 0.8);
    }
    #outer_shell #shell {
        padding-top: 11% !important;
    }
}




@media (max-width: 767px) {
    .banner-open #outer_shell #shell #banner {
        z-index: 503;
        overflow: hidden;
    }

}

@media (max-width: 500px) {

}

.s-double-tri {
    top: -23px;
    position: absolute;
    left: -29px;
}

@media (max-width: 768px) {
    #banner_inner_table {
        display: block;
    }
}

@media (max-width: 991px) {
    #shell #banner_logo img.light-logo {
        max-width: 450px !important;
    }
    #shell #banner_logo img.s-double-tri {
        max-width: 77px !important;
    }
    #banner_logo {
        padding-bottom: 10px;
    }
}

@media (max-width: 860px) {
    #banner_inner_table {
        display: block;
    }
    #banner_logo img {
        margin: 0;
    }
    #shell #banner_logo img.light-logo {
        max-width: none !important;
        top: -13px;
    }
}

@media (max-width: 767px) {
    #outer_shell #shell #banner_logo img.light-logo {
        width: 100%;
        top: -4px;
        left: 0;
        padding-right: 32px;
    }
    #outer_shell .gcui-responsive-dropdown-toggle {
        display: block;
    }
    .banner-open #shell .light-logo {
        opacity: 1;
    }
    .banner-open #outer_shell #shell #banner {
        background: rgba(0, 0, 0, 0.9);
    }
}

.banner-open #shell .s-double-tri {
    display: none;
}

@media (max-width: 400px) {
    #shell .s-double-tri {
        display: none;
    }
    #outer_shell #shell #banner {
        padding-left: 19px !important;
    }
}


</style>
<a class="logo-holder" href="/">
<img alt="Scientology Symbol" class="s-double-tri" itemprop="logo" src="/theme/images/scientology-symbol.svg"/>
<img alt="Scientology" class="light-logo" itemprop="logo" src="/theme/images/scientology-newsroom-logo.svg"/>
</a>
</div>
<div class="col w100" id="banner_tool">
<style>

#banner_tool a {
  color: #888;
  font-size: 10px;
  font-weight: bold;
}


#search_box {
    max-width: 320px;
    width: 65%;
    padding: 3px 12px 3px 12px;
    border: 1px solid silver;
    font-size: 16px;
    height: auto;
    box-shadow: none;
    border-radius: 0;
    margin-top: -4px;
}

[dir=rtl] #search_box {
    float: left !important;
}

.search-label {
    color: #666;
}

@media (max-width: 860px) {
    #banner_tool {
        display: none;
    }
}

#search_form {
    position: relative;
    margin-top: 0 !important;
    margin-bottom: 0 !important;
}

#search_form:after {
    content: "\e003";
    position: absolute;
    right: 10px;
    top: 3px;
    color: #999;
    font-family: 'Glyphicons Halflings';
    -webkit-font-smoothing: antialiased;
    font-size: 1.5em;
}

[dir=rtl] #search_form:after {
    left: 10px;
    right: auto;
}


#search_form.filled:after {
    content: "";
}



#banner_tool > .bs.pt1 {
    padding-top: 5px;
}

@media (max-width: 991px) {
    [lang="en"] .en-prim-nav-smaller-item {
        width: auto;
    }
    #banner_tool {
        font-size: 9px;
        padding-top: 2px;
    }
    #search_box {
        padding: 1px 10px 1px 5px;
    }
    #search_form {
        margin-bottom: 5px;
    }
    .primary-menu {
        table-layout: auto;
    }
}

</style>
<div class="bs pt1">
<form class="mt2 mb1" id="search_form" role="form">
<input class="form-control pull-right ml1" id="search_box" placeholder="SEARCH" type="search" value=""/>
<br clear="all"/>
</form>
</div>
</div>
</div>
</div>
<style>

#shell .primary-menu li a {
    font-size: 11px;
}

#shell .primary-menu > li > a {
    padding: 5px;
    color: rgb(50, 97, 136);
}

#shell .primary-menu > li:hover > a {
    color: rgb(255, 255, 255);
}

#shell .primary-menu li.parent ul {
    overflow: visible;
}

.primary-menu li.parent li.parent {
    position: relative;
}

.primary-menu > li.parent ul > li.parent ul {
    opacity: 0;
    left: 99%;
    top: -30px;

    pointer-events: none;
}

.primary-menu > li.parent:hover ul > li.parent:hover ul {
    opacity: 1;

    pointer-events: all;
}

.nice-menu-wrapper .row {
    display: table;
}

.nice-menu-wrapper .row:after,
.nice-menu-wrapper .row:before {
    display: none;
}

.nice-menu-wrapper .row > *,
.nice-menu-wrapper .col {
    display: table-cell;
    vertical-align: middle;
}

</style>
<div class="content nice-menu-wrapper container">
<ul class="primary-menu flat row js-menu-behavior">
<li class="parent col">
<a href="/quick-facts/">Quick Facts</a>
<ul>
<li><a href="/quick-facts/scientology.html">Scientology</a></li>
<li><a href="/quick-facts/dianetics.html">Dianetics</a></li>
<li><a href="/quick-facts/l-ron-hubbard.html">L. Ron Hubbard</a></li>
<li><a href="/quick-facts/religious-technology-center.html">Religious Technology Center (RTC)</a></li>
<li><a href="/quick-facts/church-of-scientology-international.html">Church of Scientology International</a></li>
<li><a href="/quick-facts/celebrity-centre.html">Church of Scientology Celebrity Centre International</a></li>
<li class="parent">
<a href="/quick-facts/scientology-volunteer-ministers.html">Social Betterment Campaigns</a>
<ul>
<li><a href="/quick-facts/scientology-volunteer-ministers.html">Scientology Volunteer Ministers</a></li>
<li><a href="/quick-facts/applied-scholastics.html">Anti-Drug Campaign</a></li>
<li><a href="/quick-facts/human-rights-scientology.html">Human Rights</a></li>
<li><a href="/quick-facts/community-outreach-actions.html">Community Outreach</a></li>
</ul>
</li>
<li class="parent">
<a href="/quick-facts/association-for-better-living-and-education.html">Association for Better Living and Education</a>
<ul>
<li><a href="/quick-facts/association-for-better-living-and-education.html">ABLE International</a></li>
<li><a href="/quick-facts/drug-prevention.html">Applied Scholastics International</a></li>
<li><a href="/quick-facts/criminon.html">Criminon</a></li>
<li><a href="/quick-facts/narconon.html">Narconon</a></li>
<li><a href="/quick-facts/the-way-to-happiness.html">The Way to Happiness Foundation</a></li>
</ul>
</li>
</ul>
</li>
<li class="parent col">
<a href="/press-releases/">Press Releases</a>
<ul>
<li><a href="/press-releases/church-openings/">New Churches of Scientology Grand Opening</a></li>
<li><a href="/press-releases/activities/">Church of Scientology Activities</a></li>
<li><a href="/press-releases/meet-scientologists/">Meet a Scientologist</a></li>
<li><a href="/press-releases/religious-freedom/">Scientology and Religious Freedom</a></li>
</ul>
</li>
<li class="col">
<a href="/stats.html">Statistics</a>
</li>
<li class="parent col">
<a href="/image-gallery/">Photos</a>
<ul>
<li>
<a href="/image-gallery/l-ron-hubbard.html">
                           L. Ron Hubbard, Founder
                    </a>
</li>
<li>
<a href="/image-gallery/new-churches-of-scientology/">
                        New Churches of Scientology
                    </a>
</li>
<li>
<a href="/image-gallery/international-dissemination-facilities/">
                          International Dissemination Facilities
                   </a>
</li>
<li>
<a href="/image-gallery/international-events/">
                          International Events
                   </a>
</li>
<li>
<a href="/image-gallery/david-miscavige.html">
                          David Miscavige, Ecclesiastical Leader of the Scientology Religion
                   </a>
</li>
<li>
<a href="/image-gallery/global-social-betterment-humanitarian-programs/">
                          Global Social Betterment &amp; Humanitarian Programs Supported by the Church
                   </a>
</li>
</ul>
</li>
<li class="col">
<a href="/faq/frequently-asked-questions-introduction.html">Frequently Asked Questions</a>
</li>
<li class="col en-prim-nav-smaller-item">
<a href="/contact.html">Contact</a>
</li>
</ul>
</div>
<style>



.banner-open .banner-toggle {
    background: url(/theme/images/home-mobile-trigger-open-xparent.png) center no-repeat;
    z-index: 512;
    position: fixed;

}

:lang(en).banner-open .banner-toggle {
    z-index: 504;

}

.banner-toggle {
    font-size: 20px;
    position: absolute;
    top: 2%;
    right: 10px;
    margin: 0 10px 0 0;
    background: url(/theme/images/home-mobile-trigger-xparent.png) center no-repeat;
    width: 48px;
    height: 48px;
    cursor: pointer;
}

@media (max-width: 580px) {
    .banner-toggle {
        top: 1%;
    }
}

@media (max-width: 520px) {
    #shell .banner-toggle {
        width: 36px;
        height: 36px;
        background-size: cover;
        top: 0./%;
    }
}

@media (max-width: 400px) {
    #shell .banner-toggle {
        top: 0.5%;
        width: 32px;
        height: 32px;
    }
}


:lang(en) .banner-toggle {
    margin: 0 0 0 10px;
    background: url(/theme/images/home-mobile-trigger-xparent-new.png) center no-repeat transparent;
}

[dir="rtl"] .banner-toggle {
    margin: 0 0 0 10px;
    right: auto;
    left: 0;
}



#banner_mobile {
    text-align: right;
}

#banner_fixed_holder {
    position: fixed;
    top: 66px;
    bottom: 0;
    left: 0;
    right: 0;
    z-index: 502;
}

:lang(en) #banner_fixed_holder {
    top: 0;
    padding-top: 66px;
    -webkit-transition: position .1s cubic-bezier(0.165, 0.840, 0.440, 1.000) .1s;
    -moz-transition: position .1s cubic-bezier(0.165, 0.840, 0.440, 1.000) .1s;
    -o-transition: position .1s cubic-bezier(0.165, 0.840, 0.440, 1.000) .1s;
    transition: position .1s cubic-bezier(0.165, 0.840, 0.440, 1.000) .1s;
}

@media (max-width: 500px) {
    :lang(en) #banner_fixed_holder {
        padding-top: 36px;
    }
}

#banner_tool_inner_mobile .dark-logo {
    display: none;
}


### **Step 3:** find all the div elements with the article classes, which contain the property announcements for scraping.

In [159]:
items = doc.find_all('div', class_='article') 

print(len(items)) #gives you the number of items found from webpage. When I first did this it only printed 20 items b/c it only scraped page 1 of 5.

20

### **Step 4:** Check the first instance to see what the data looks like to proceed with scraping

In [160]:
items[0] #prints out the html for the first article out of the 20 it found on page 1.

#FOUND:

#article title = h3, class = article-title (can see title in bold next to it)
#date = nobr (in all caps by the location tag)
#location = span, location-color (can see by the location in all caps below)

<div class="article blocked-hover" data-art-id="/press-releases/church-openings/oceanview-grand-opening.html">
<div class="media article-header-container">
<div class="media-left type-logo-container">
<img class="media-object type-logo" src="/theme/images/nr-logo.svg"/>
</div>
<div class="media-body article-title-container">
<h3 class="title article-title"><a href="/press-releases/church-openings/oceanview-grand-opening.html">NEW WATERFRONT RELIGIOUS RETREAT OPENS AT SCIENTOLOGY SPIRITUAL HEADQUARTERS IN CLEARWATER</a></h3>
</div>
</div>
<div class="row">
<div class="col-md-8">
<div class="inline-img-block inline-img-block-30">
<a href="/press-releases/church-openings/oceanview-grand-opening.html">
<img class="img-responsive" itemprop="image" src="https://files.scientology.org/imagecache/cropfit@w=224@cp=v1-onscQECenSjw64icV3veTA@dm=3600x2400@sig=ca6uuF-HMf/data/www.scientology.org/files/press-release/oceanview-grand-opening/oceanview-grand-opening_06c3875--listing_en.jpg" srcset="https://files.scientology.org/imagecache/cropfit@w=224@cp=v1-onscQECenSjw64icV3veTA@dm=3600x2400@sig=ca6uuF-HMf/data/www.scientology.org/files/press-release/oceanview-grand-opening/oceanview-grand-opening_06c3875--listing_en.jpg 1x, https://files.scientology.org/imagecache/cropfit@w=448@cp=v1-onscQECenSjw64icV3veTA@dm=3600x2400@sig=ca6uuF-HMf/data/www.scientology.org/files/press-release/oceanview-grand-opening/oceanview-grand-opening_06c3875--listing_en.jpg 2x"/>
</a>
</div>
</div>
<div class="col-md-16">
<p class="location-date">
<span class="location-color">CLEARWATER, FLORIDA</span> • <nobr>SATURDAY, APRIL 25, 2026</nobr>
</p>
<p>Thousands gathered for the opening of the Oceanview, a striking new seven-story waterfront religious retreat overlooking Clearwater Bay, created to serve parishioners arriving for advanced religious services at the Church’s international spiritual headquarters—Flag.</p>
<p class="clearfix"><a class="learn-more pull-right flip" href="/press-releases/church-openings/oceanview-grand-opening.html" target="_self">Full Story »</a></p>
</div>
</div>
</div>

### **Below will be the initial stage of the data analysis**

### **Step 5:** Pulling data from the website using what was found above.

In [161]:
rows = []

for offset in range(0, 200, 20): #200 is more than real # of articles, but not less. 20 is what it grows by end of url each page.
    url = f"https://www.scientologynews.org/press-releases/church-openings/?from={offset}" #{offset} = end of URL where # changes.
    
    response = requests.get(url) #needed to add this line and the code below since the ^ URL essentially loops/creates a new one. 
    doc = BeautifulSoup(response.text, 'html.parser')
    
    items = doc.find_all('div', class_='article')
    
    for item in items:
        
        rows.append({
            'title': item.find('h3', class_='article-title').get_text(strip=True),
            'location': item.find('span', class_='location-color').get_text(strip=True),
            'date': item.find('nobr').get_text(strip=True) 
        }) #I found that doing rows.appead at the top is faster than defining it at the end.

In [83]:
#This is my commented out OG code. It worked and found all the info from first page, but I needed all 5. Each time you
#go to a new page though, the end of the URL changed. It starts with nothing on the end then goes to ?from=20, 40, 60, 80.


#rows = [] 
#put the info for the article titles, their location, and the date for the openings below. refer to items[0].
#put them ^^^ into a for loop for items to get the info for the 3 pieces below i need for project.

#for item in items:
    #print("-"*40) #soma trick for ----- line.
    #row = { #this is the start of a dictionary.
        #'title': item.find('h3', class_='article-title').get_text(strip=True),
        #'location': item.find('span', class_='location-color').get_text(strip=True),
        #'date': item.find('nobr').get_text(strip=True)
   # }

   # print(row) #shows items that were extracted in dictionary.
   # rows.append(row) #adds dictionary to the list.

### **Step 6:** Run the code below to see all of your data.

In [163]:
df = pd.DataFrame(rows) #this originally showed only a portion of the rows but now prints all.

In [164]:
df

,title,location,date
0,NEW WATERFRONT RELIGIOUS RETREAT OPENS AT SCIE...,"CLEARWATER, FLORIDA","SATURDAY, APRIL 25, 2026"
1,CARIBBEAN CALLING: PUERTO RICAN PRIDE SHINES W...,"SAN JUAN, PUERTO RICO","SUNDAY, FEBRUARY 22, 2026"
2,TEN STORIES OF TRIUMPH FOR SOUTH AFRICA AS NEW...,"GQEBERHA, EASTERN CAPE, SOUTH AFRICA","SUNDAY, APRIL 6, 2025"
3,DAZZLING NEW SCIENTOLOGY IDEAL ORG SHINES BRIG...,"PARIS, FRANCE","SATURDAY, APRIL 6, 2024"
4,BIG NEWS IN THE CITY OF BIG SHOULDERS AS SCIEN...,"CHICAGO, ILLINOIS","SUNDAY, MARCH 3, 2024"
5,MEXICO CITY’S NIGHT SKY LIGHTS UP WITH OPENING...,"MEXICO CITY, MEXICO","FRIDAY, MARCH 1, 2024"
6,NEW SCIENTOLOGY STAR RISES IN TEXAS’SALL-STARC...,"AUSTIN, TEXAS","SATURDAY, FEBRUARY 24, 2024"
7,CHURCH OF SCIENTOLOGY ANSWERS ONGOING EUROPEAN...,"COPENHAGEN, DENMARK","SUNDAY, NOVEMBER 12, 2023"
8,IGNITING A NEW ERA OF EXPANSION FOR SCIENTOLOG...,"EAST GRINSTEAD, ENGLAND","SUNDAY, NOVEMBER 5, 2023"
9,SCIENTOLOGY IDEAL ORG RISES LIKE A LEGENDARY K...,"VENTURA, CALIFORNIA","SATURDAY, FEBRUARY 22, 2020"
10,O-H-I-O: NEW CHURCH OF SCIENTOLOGY KICKS OFF I...,"COLUMBUS, CENTRAL OHIO","SATURDAY, NOVEMBER 9, 2019"
11,A NEW HOME IN THE HEARTLAND: CHURCH OF SCIENTO...,"KANSAS CITY, MISSOURI","SATURDAY, NOVEMBER 2, 2019"
12,WINDS OF CHANGE: SCIENTOLOGY HEADQUARTERS FOR ...,"JOHANNESBURG, SOUTH AFRICA","TUESDAY, JANUARY 1, 2019"
13,MADE IN DETROIT: NEW CHURCH OF SCIENTOLOGY NOW...,"DETROIT, MICHIGAN","SUNDAY, OCTOBER 14, 2018"
14,NEW SCIENTOLOGY MISSION OF COMO GRACES NORTHER...,"COMO, ITALY","SUNDAY, SEPTEMBER 30, 2018"
15,FREEDOM REIGNS AS THE CHURCH OF SCIENTOLOGY ST...,"STUTTGART, GERMANY","SUNDAY, SEPTEMBER 9, 2018"
16,A STAR BURSTS IN “THE CITY BEAUTIFUL” AS A RIB...,"ORLANDO, FLORIDA","SATURDAY, MAY 12, 2018"
17,DOWN UNDER’S “CITY OF LIGHTS” WELCOMES NEWEST ...,"PERTH, WESTERN AUSTRALIA","SATURDAY, MAY 5, 2018"
18,WHERE SPIRITUALITY INTERSECTS WITH HUMAN BRILL...,"SILICON VALLEY, CALIFORNIA","SUNDAY, FEBRUARY 18, 2018"
19,"IN THE SPIRIT OF ITS HISTORIC PIONEERS, CITY O...","SALT LAKE CITY, UTAH","SATURDAY, FEBRUARY 17, 2018"
20,SCIENTOLOGY OPENS DOORS TO NEW IDEAL MISSION I...,"KOŠICE, SLOVAKIA","SATURDAY, JANUARY 13, 2018"
21,FESTIVE SPIRIT: JOHANNESBURG WELCOMES NEW CHUR...,"JOBURG NORTH, SOUTH AFRICA","SATURDAY, DECEMBER 23, 2017"
22,A REVOLUTION OF THE SPIRIT IN BRITAIN’S SALT O...,"BIRMINGHAM, ENGLAND","SATURDAY, OCTOBER 21, 2017"
23,DEDICATING THE NEW IDEAL MISSION OF SCIENTOLOG...,"SENIGALLIA, ITALY","THURSDAY, SEPTEMBER 28, 2017"
24,CELEBRATING 30 YEARS OF SERVICE TO BATON ROUGE...,"BATON ROUGE, LOUISIANA","SATURDAY, JULY 8, 2017"
25,DANISH DELIGHT: A NEW CHURCH OF SCIENTOLOGY IS...,"COPENHAGEN, DENMARK","SATURDAY, MAY 27, 2017"
26,A MAGICAL WELCOME GREETS MIAMI’S NEW CHURCH OF...,"MIAMI, FLORIDA","SATURDAY, APRIL 29, 2017"
27,NORTH AMERICA’S LARGEST CHURCH OF SCIENTOLOGY ...,"SAN FERNANDO VALLEY, CALIFORNIA","SUNDAY, MARCH 19, 2017"
28,A TREASURED LANDMARK REBORN—SCIENTOLOGY OPENS ...,"AUCKLAND, NEW ZEALAND","SATURDAY, JANUARY 21, 2017"
29,CALIFORNIA DREAMING BECOMES REALITY AS SAN DIE...,"SAN DIEGO, CALIFORNIA","SATURDAY, NOVEMBER 19, 2016"
30,CHURCH OF SCIENTOLOGY OPENS DOORS TO NEW IDEAL...,"LAKE FOREST, CALIFORNIA","SUNDAY, OCTOBER 23, 2016"
31,CHURCH OF SCIENTOLOGY CUTS A RIBBON ON NATIONA...,"DUBLIN, IRELAND","SATURDAY, OCTOBER 15, 2016"
32,SCIENTOLOGY CROWNS RECORD GROWTH WITH ALL-NEW ...,"SYDNEY, AUSTRALIA","SUNDAY, SEPTEMBER 4, 2016"
33,A NEW ROSE BLOOMS: IDEAL ORG AND COMMUNITY CEN...,"HARLEM, NEW YORK","SUNDAY, JULY 31, 2016"
34,A SAGA OF FREEDOM CULMINATES IN IDEAL CHURCH C...,"BUDAPEST, HUNGARY","SATURDAY, JULY 23, 2016"
35,CHURCH TRANSFORMS TWO CLEARWATER BUILDINGS INT...,"CLEARWATER, FLORIDA","SATURDAY, JUNE 25, 2016"
36,SCIENTOLOGY MEDIA PRODUCTIONS LAUNCHES IN HOLL...,"LOS ANGELES, CALIFORNIA","SATURDAY, MAY 28, 2016"
37,ATLANTA’S SPIRIT OF FREEDOM SHINES BRIGHT AS G...,"ATLANTA, GEORGIA","SATURDAY, APRIL 2, 2016"
38,CHURCH OF SCIENTOLOGY DEDICATES LANDMARK BUILD...,"CLEARWATER, FLORIDA","SUNDAY, JUNE 29, 2014"
39,NEW IDEAL ORG IN THE HEART OF AUSTRALIA’S HARB...,"SYDNEY, AUSTRALIA","SATURDAY, MAY 3, 2014"
40,AN IDEAL ORG AT THE GATEWAY OF THE CHINESE-SPE...,"KAOHSIUNG, TAIWAN","SATURDAY, DECEMBER 7, 2013"
41,CHURCH OF SCIENTOLOGY MISSION OPENS DOORS TO N...,"LOS ANGELES, CALIFORNIA","SUNDAY, AUGUST 25, 2013"
42,NEW IDEAL CHURCH OF SCIENTOLOGY BLOOMS IN THE ...,"PORTLAND, OREGON","SATURDAY, MAY 11, 2013"
43,SOUTH AFRICAN CAPITAL HERALDS NEW CHURCH OF SC...,"PRETORIA, GAUTENG","SATURDAY, FEBRUARY 23, 2013"
44,CHURCH OF SCIENTOLOGY CUTS RIBBON ON NEW IDEAL...,"CAMBRIDGE, ONTARIO","SATURDAY, FEBRUARY 9, 2013"
45,THOUSANDS CELEBRATE NEW SCIENTOLOGY CHURCH IN ...,"PADUA, ITALY","SATURDAY, OCTOBER 27, 2012"
46,CHURCH OF SCIENTOLOGY OPENS NATIONAL OFFICE IN...,"WASHINGTON, D.C.","WEDNESDAY, SEPTEMBER 12, 2012"
47,RIBBON FALLS ON IDEAL CENTER OF SCIENTOLOGY FO...,"TEL AVIV, ISRAEL","TUESDAY, AUGUST 21, 2012"
48,BAY AREA SCIENTOLOGISTS REDEDICATE IDEAL CHURC...,"LOS GATOS, CALIFORNIA","SATURDAY, JULY 28, 2012"
49,SCIENTOLOGISTS CUT THE RIBBON ON LANDMARK BUFF...,"BUFFALO, NEW YORK","SATURDAY, JUNE 30, 2012"
50,RIBBON FALLS ON IDEAL ORG IN THE BIRTHPLACE OF...,"PHOENIX, ARIZONA","SATURDAY, JUNE 23, 2012"
51,NEW IDEAL CHURCH OF SCIENTOLOGY FOR THE MILE-H...,"DENVER, COLORADO","SATURDAY, JUNE 16, 2012"
52,SCIENTOLOGY REBOOTS IDEAL CHURCH IN SILICON VA...,"SAN JOSE, CALIFORNIA","SATURDAY, JUNE 9, 2012"
53,ORANGE COUNTY WELCOMES CHURCH OF SCIENTOLOGY T...,"SANTA ANA, CALIFORNIA","SATURDAY, JUNE 2, 2012"
54,SCIENTOLOGY CHURCH OPENS DOORS TO A TRI-STATE ...,GREATER CINCINNATI,"SATURDAY, FEBRUARY 25, 2012"
55,CHURCH OF SCIENTOLOGY INAUGURATES NEW LANDMARK...,"SACRAMENTO, CALIFORNIA","SATURDAY, JANUARY 28, 2012"
56,HAMBURG DEDICATES A NEW IDEAL CHURCH OF SCIENT...,"HAMBURG, GERMANY","SATURDAY, JANUARY 21, 2012"
57,CHURCH OF SCIENTOLOGY INGLEWOOD—VIDEO FOOTAGE ...,"INGLEWOOD, CALIFORNIA","SATURDAY, NOVEMBER 5, 2011"
58,CHURCH OF SCIENTOLOGY CELEBRATES THE OPENING O...,"INGLEWOOD, CALIFORNIA","SATURDAY, NOVEMBER 5, 2011"
59,CHURCH OF SCIENTOLOGY CUTS RIBBON ON TWIN CITI...,"ST. PAUL, MINNESOTA","SATURDAY, OCTOBER 22, 2011"
60,JOHN TRAVOLTA OPENS CHURCH OF SCIENTOLOGY MISS...,"OCALA, FLORIDA, USA","SUNDAY, MAY 29, 2011"
61,CHURCH OF SCIENTOLOGY OF TAMPA EXPANDS INTO NE...,"TAMPA, FLORIDA","SUNDAY, MARCH 13, 2011"
62,RIBBON FALLS ON AUSTRALIA’S FIRST IDEAL CHURCH...,"MELBOURNE, AUSTRALIA","SATURDAY, JANUARY 29, 2011"
63,SCIENTOLOGY OPENS RECORD NUMBER OF NEW CHURCHE...,LOS ANGELES,"THURSDAY, JANUARY 27, 2011"
64,"CHURCH OF SCIENTOLOGY FLIPS THE SWITCH ON 185,...",LOS ANGELES,"WEDNESDAY, JANUARY 26, 2011"
65,CHURCH OF SCIENTOLOGY DEDICATES NEW BUILDING F...,"SEATTLE, WASHINGTON","SATURDAY, JULY 24, 2010"
66,"NEW IDEAL SCIENTOLOGY CHURCH IN PASADENA, CALI...","PASADENA, CALIFORNIA","SUNDAY, JULY 18, 2010"
67,SCIENTOLOGY OPENS NEW NATIONAL ORGANIZATION FO...,"MEXICO CITY, MEXICO","SATURDAY, JULY 10, 2010"
68,CHURCH OF SCIENTOLOGY OF LOS ANGELES OPENS NEW...,"LOS ANGELES, CALIFORNIA","SATURDAY, APRIL 24, 2010"
69,SCIENTOLOGY LIFE IMPROVEMENT CENTRE OPENS IN J...,"JOHANNESBURG, SOUTH AFRICA","FRIDAY, MARCH 26, 2010"
70,"NEW 40,000-SQUARE-FOOT CHURCH OF SCIENTOLOGY O...","LAS VEGAS, NEVADA","SATURDAY, FEBRUARY 6, 2010"
71,NEW CHURCH IN THE HISTORIC HEART OF FRENCH CANADA,"QUÉBEC, CANADA","SATURDAY, JANUARY 30, 2010"
72,NEW BRANCH OF CHURCHES OF SCIENTOLOGY FOR EURO...,"BRUSSELS, BELGIUM","SATURDAY, JANUARY 23, 2010"
73,FOUNDING CHURCH OF SCIENTOLOGY GRAND OPENING I...,"WASHINGTON, DC","SATURDAY, OCTOBER 31, 2009"
74,NEW CHURCH OF SCIENTOLOGY OPENS DOORS TO ROME,"ROME, ITALY","SATURDAY, OCTOBER 24, 2009"
75,CHURCH OF SCIENTOLOGY OPENS NEW CELEBRITY CENT...,"NASHVILLE, TENNESSEE","SATURDAY, APRIL 25, 2009"
76,SCIENTOLOGY OPENS NEW CHURCH IN DALLAS,"DALLAS, TEXAS","SATURDAY, APRIL 11, 2009"
77,THE KNOWLEDGE CENTER OF NORTHERN EUROPE,"MALMÖ, SWEDEN","SATURDAY, APRIL 4, 2009"
78,THE LANDMARK FORT HARRISON FULLY RESTORED,"CLEARWATER, FLORIDA","SATURDAY, MARCH 14, 2009"
79,SCIENTOLOGY OPENS PROMINENT NEW CHURCH IN BERLIN,"BERLIN, GERMANY","SATURDAY, JANUARY 13, 2007"
80,SPECTACULAR GRAND OPENING OF THE CHURCH OF SCI...,"LONDON, ENGLAND","SUNDAY, OCTOBER 22, 2006"
81,CHURCH OF SCIENTOLOGY OF NEW YORK INAUGURATES ...,"NEW YORK, NEW YORK","SUNDAY, SEPTEMBER 26, 2004"
82,THE NATIONAL CHURCH OF SCIENTOLOGY OPENED IN T...,"MADRID, SPAIN","SATURDAY, SEPTEMBER 18, 2004"
83,ORIGINAL TRANSAMERICA BUILDING IS RESTORED AS ...,"SAN FRANCISCO, CALIFORNIA","SATURDAY, NOVEMBER 29, 2003"
84,CHURCH OF SCIENTOLOGY OF JOHANNESBURG OPENS TH...,"JOHANNESBURG, SOUTH AFRICA","SATURDAY, NOVEMBER 1, 2003"

In [146]:
pd.set_option('display.max_rows', None)
display(df)

#when the cell above only ran some rows, google said to run the code in this cell to see all parts of my df.

,title,location,date
0,NEW WATERFRONT RELIGIOUS RETREAT OPENS AT SCIE...,"CLEARWATER, FLORIDA","SATURDAY, APRIL 25, 2026"
1,CARIBBEAN CALLING: PUERTO RICAN PRIDE SHINES W...,"SAN JUAN, PUERTO RICO","SUNDAY, FEBRUARY 22, 2026"
2,TEN STORIES OF TRIUMPH FOR SOUTH AFRICA AS NEW...,"GQEBERHA, EASTERN CAPE, SOUTH AFRICA","SUNDAY, APRIL 6, 2025"
3,DAZZLING NEW SCIENTOLOGY IDEAL ORG SHINES BRIG...,"PARIS, FRANCE","SATURDAY, APRIL 6, 2024"
4,BIG NEWS IN THE CITY OF BIG SHOULDERS AS SCIEN...,"CHICAGO, ILLINOIS","SUNDAY, MARCH 3, 2024"
5,MEXICO CITY’S NIGHT SKY LIGHTS UP WITH OPENING...,"MEXICO CITY, MEXICO","FRIDAY, MARCH 1, 2024"
6,NEW SCIENTOLOGY STAR RISES IN TEXAS’SALL-STARC...,"AUSTIN, TEXAS","SATURDAY, FEBRUARY 24, 2024"
7,CHURCH OF SCIENTOLOGY ANSWERS ONGOING EUROPEAN...,"COPENHAGEN, DENMARK","SUNDAY, NOVEMBER 12, 2023"
8,IGNITING A NEW ERA OF EXPANSION FOR SCIENTOLOG...,"EAST GRINSTEAD, ENGLAND","SUNDAY, NOVEMBER 5, 2023"
9,SCIENTOLOGY IDEAL ORG RISES LIKE A LEGENDARY K...,"VENTURA, CALIFORNIA","SATURDAY, FEBRUARY 22, 2020"
10,O-H-I-O: NEW CHURCH OF SCIENTOLOGY KICKS OFF I...,"COLUMBUS, CENTRAL OHIO","SATURDAY, NOVEMBER 9, 2019"
11,A NEW HOME IN THE HEARTLAND: CHURCH OF SCIENTO...,"KANSAS CITY, MISSOURI","SATURDAY, NOVEMBER 2, 2019"
12,WINDS OF CHANGE: SCIENTOLOGY HEADQUARTERS FOR ...,"JOHANNESBURG, SOUTH AFRICA","TUESDAY, JANUARY 1, 2019"
13,MADE IN DETROIT: NEW CHURCH OF SCIENTOLOGY NOW...,"DETROIT, MICHIGAN","SUNDAY, OCTOBER 14, 2018"
14,NEW SCIENTOLOGY MISSION OF COMO GRACES NORTHER...,"COMO, ITALY","SUNDAY, SEPTEMBER 30, 2018"
15,FREEDOM REIGNS AS THE CHURCH OF SCIENTOLOGY ST...,"STUTTGART, GERMANY","SUNDAY, SEPTEMBER 9, 2018"
16,A STAR BURSTS IN “THE CITY BEAUTIFUL” AS A RIB...,"ORLANDO, FLORIDA","SATURDAY, MAY 12, 2018"
17,DOWN UNDER’S “CITY OF LIGHTS” WELCOMES NEWEST ...,"PERTH, WESTERN AUSTRALIA","SATURDAY, MAY 5, 2018"
18,WHERE SPIRITUALITY INTERSECTS WITH HUMAN BRILL...,"SILICON VALLEY, CALIFORNIA","SUNDAY, FEBRUARY 18, 2018"
19,"IN THE SPIRIT OF ITS HISTORIC PIONEERS, CITY O...","SALT LAKE CITY, UTAH","SATURDAY, FEBRUARY 17, 2018"
20,SCIENTOLOGY OPENS DOORS TO NEW IDEAL MISSION I...,"KOŠICE, SLOVAKIA","SATURDAY, JANUARY 13, 2018"
21,FESTIVE SPIRIT: JOHANNESBURG WELCOMES NEW CHUR...,"JOBURG NORTH, SOUTH AFRICA","SATURDAY, DECEMBER 23, 2017"
22,A REVOLUTION OF THE SPIRIT IN BRITAIN’S SALT O...,"BIRMINGHAM, ENGLAND","SATURDAY, OCTOBER 21, 2017"
23,DEDICATING THE NEW IDEAL MISSION OF SCIENTOLOG...,"SENIGALLIA, ITALY","THURSDAY, SEPTEMBER 28, 2017"
24,CELEBRATING 30 YEARS OF SERVICE TO BATON ROUGE...,"BATON ROUGE, LOUISIANA","SATURDAY, JULY 8, 2017"
25,DANISH DELIGHT: A NEW CHURCH OF SCIENTOLOGY IS...,"COPENHAGEN, DENMARK","SATURDAY, MAY 27, 2017"
26,A MAGICAL WELCOME GREETS MIAMI’S NEW CHURCH OF...,"MIAMI, FLORIDA","SATURDAY, APRIL 29, 2017"
27,NORTH AMERICA’S LARGEST CHURCH OF SCIENTOLOGY ...,"SAN FERNANDO VALLEY, CALIFORNIA","SUNDAY, MARCH 19, 2017"
28,A TREASURED LANDMARK REBORN—SCIENTOLOGY OPENS ...,"AUCKLAND, NEW ZEALAND","SATURDAY, JANUARY 21, 2017"
29,CALIFORNIA DREAMING BECOMES REALITY AS SAN DIE...,"SAN DIEGO, CALIFORNIA","SATURDAY, NOVEMBER 19, 2016"
30,CHURCH OF SCIENTOLOGY OPENS DOORS TO NEW IDEAL...,"LAKE FOREST, CALIFORNIA","SUNDAY, OCTOBER 23, 2016"
31,CHURCH OF SCIENTOLOGY CUTS A RIBBON ON NATIONA...,"DUBLIN, IRELAND","SATURDAY, OCTOBER 15, 2016"
32,SCIENTOLOGY CROWNS RECORD GROWTH WITH ALL-NEW ...,"SYDNEY, AUSTRALIA","SUNDAY, SEPTEMBER 4, 2016"
33,A NEW ROSE BLOOMS: IDEAL ORG AND COMMUNITY CEN...,"HARLEM, NEW YORK","SUNDAY, JULY 31, 2016"
34,A SAGA OF FREEDOM CULMINATES IN IDEAL CHURCH C...,"BUDAPEST, HUNGARY","SATURDAY, JULY 23, 2016"
35,CHURCH TRANSFORMS TWO CLEARWATER BUILDINGS INT...,"CLEARWATER, FLORIDA","SATURDAY, JUNE 25, 2016"
36,SCIENTOLOGY MEDIA PRODUCTIONS LAUNCHES IN HOLL...,"LOS ANGELES, CALIFORNIA","SATURDAY, MAY 28, 2016"
37,ATLANTA’S SPIRIT OF FREEDOM SHINES BRIGHT AS G...,"ATLANTA, GEORGIA","SATURDAY, APRIL 2, 2016"
38,CHURCH OF SCIENTOLOGY DEDICATES LANDMARK BUILD...,"CLEARWATER, FLORIDA","SUNDAY, JUNE 29, 2014"
39,NEW IDEAL ORG IN THE HEART OF AUSTRALIA’S HARB...,"SYDNEY, AUSTRALIA","SATURDAY, MAY 3, 2014"
40,AN IDEAL ORG AT THE GATEWAY OF THE CHINESE-SPE...,"KAOHSIUNG, TAIWAN","SATURDAY, DECEMBER 7, 2013"
41,CHURCH OF SCIENTOLOGY MISSION OPENS DOORS TO N...,"LOS ANGELES, CALIFORNIA","SUNDAY, AUGUST 25, 2013"
42,NEW IDEAL CHURCH OF SCIENTOLOGY BLOOMS IN THE ...,"PORTLAND, OREGON","SATURDAY, MAY 11, 2013"
43,SOUTH AFRICAN CAPITAL HERALDS NEW CHURCH OF SC...,"PRETORIA, GAUTENG","SATURDAY, FEBRUARY 23, 2013"
44,CHURCH OF SCIENTOLOGY CUTS RIBBON ON NEW IDEAL...,"CAMBRIDGE, ONTARIO","SATURDAY, FEBRUARY 9, 2013"
45,THOUSANDS CELEBRATE NEW SCIENTOLOGY CHURCH IN ...,"PADUA, ITALY","SATURDAY, OCTOBER 27, 2012"
46,CHURCH OF SCIENTOLOGY OPENS NATIONAL OFFICE IN...,"WASHINGTON, D.C.","WEDNESDAY, SEPTEMBER 12, 2012"
47,RIBBON FALLS ON IDEAL CENTER OF SCIENTOLOGY FO...,"TEL AVIV, ISRAEL","TUESDAY, AUGUST 21, 2012"
48,BAY AREA SCIENTOLOGISTS REDEDICATE IDEAL CHURC...,"LOS GATOS, CALIFORNIA","SATURDAY, JULY 28, 2012"
49,SCIENTOLOGISTS CUT THE RIBBON ON LANDMARK BUFF...,"BUFFALO, NEW YORK","SATURDAY, JUNE 30, 2012"
50,RIBBON FALLS ON IDEAL ORG IN THE BIRTHPLACE OF...,"PHOENIX, ARIZONA","SATURDAY, JUNE 23, 2012"
51,NEW IDEAL CHURCH OF SCIENTOLOGY FOR THE MILE-H...,"DENVER, COLORADO","SATURDAY, JUNE 16, 2012"
52,SCIENTOLOGY REBOOTS IDEAL CHURCH IN SILICON VA...,"SAN JOSE, CALIFORNIA","SATURDAY, JUNE 9, 2012"
53,ORANGE COUNTY WELCOMES CHURCH OF SCIENTOLOGY T...,"SANTA ANA, CALIFORNIA","SATURDAY, JUNE 2, 2012"
54,SCIENTOLOGY CHURCH OPENS DOORS TO A TRI-STATE ...,GREATER CINCINNATI,"SATURDAY, FEBRUARY 25, 2012"
55,CHURCH OF SCIENTOLOGY INAUGURATES NEW LANDMARK...,"SACRAMENTO, CALIFORNIA","SATURDAY, JANUARY 28, 2012"
56,HAMBURG DEDICATES A NEW IDEAL CHURCH OF SCIENT...,"HAMBURG, GERMANY","SATURDAY, JANUARY 21, 2012"
57,CHURCH OF SCIENTOLOGY INGLEWOOD—VIDEO FOOTAGE ...,"INGLEWOOD, CALIFORNIA","SATURDAY, NOVEMBER 5, 2011"
58,CHURCH OF SCIENTOLOGY CELEBRATES THE OPENING O...,"INGLEWOOD, CALIFORNIA","SATURDAY, NOVEMBER 5, 2011"
59,CHURCH OF SCIENTOLOGY CUTS RIBBON ON TWIN CITI...,"ST. PAUL, MINNESOTA","SATURDAY, OCTOBER 22, 2011"
60,JOHN TRAVOLTA OPENS CHURCH OF SCIENTOLOGY MISS...,"OCALA, FLORIDA, USA","SUNDAY, MAY 29, 2011"
61,CHURCH OF SCIENTOLOGY OF TAMPA EXPANDS INTO NE...,"TAMPA, FLORIDA","SUNDAY, MARCH 13, 2011"
62,RIBBON FALLS ON AUSTRALIA’S FIRST IDEAL CHURCH...,"MELBOURNE, AUSTRALIA","SATURDAY, JANUARY 29, 2011"
63,SCIENTOLOGY OPENS RECORD NUMBER OF NEW CHURCHE...,LOS ANGELES,"THURSDAY, JANUARY 27, 2011"
64,"CHURCH OF SCIENTOLOGY FLIPS THE SWITCH ON 185,...",LOS ANGELES,"WEDNESDAY, JANUARY 26, 2011"
65,CHURCH OF SCIENTOLOGY DEDICATES NEW BUILDING F...,"SEATTLE, WASHINGTON","SATURDAY, JULY 24, 2010"
66,"NEW IDEAL SCIENTOLOGY CHURCH IN PASADENA, CALI...","PASADENA, CALIFORNIA","SUNDAY, JULY 18, 2010"
67,SCIENTOLOGY OPENS NEW NATIONAL ORGANIZATION FO...,"MEXICO CITY, MEXICO","SATURDAY, JULY 10, 2010"
68,CHURCH OF SCIENTOLOGY OF LOS ANGELES OPENS NEW...,"LOS ANGELES, CALIFORNIA","SATURDAY, APRIL 24, 2010"
69,SCIENTOLOGY LIFE IMPROVEMENT CENTRE OPENS IN J...,"JOHANNESBURG, SOUTH AFRICA","FRIDAY, MARCH 26, 2010"
70,"NEW 40,000-SQUARE-FOOT CHURCH OF SCIENTOLOGY O...","LAS VEGAS, NEVADA","SATURDAY, FEBRUARY 6, 2010"
71,NEW CHURCH IN THE HISTORIC HEART OF FRENCH CANADA,"QUÉBEC, CANADA","SATURDAY, JANUARY 30, 2010"
72,NEW BRANCH OF CHURCHES OF SCIENTOLOGY FOR EURO...,"BRUSSELS, BELGIUM","SATURDAY, JANUARY 23, 2010"
73,FOUNDING CHURCH OF SCIENTOLOGY GRAND OPENING I...,"WASHINGTON, DC","SATURDAY, OCTOBER 31, 2009"
74,NEW CHURCH OF SCIENTOLOGY OPENS DOORS TO ROME,"ROME, ITALY","SATURDAY, OCTOBER 24, 2009"
75,CHURCH OF SCIENTOLOGY OPENS NEW CELEBRITY CENT...,"NASHVILLE, TENNESSEE","SATURDAY, APRIL 25, 2009"
76,SCIENTOLOGY OPENS NEW CHURCH IN DALLAS,"DALLAS, TEXAS","SATURDAY, APRIL 11, 2009"
77,THE KNOWLEDGE CENTER OF NORTHERN EUROPE,"MALMÖ, SWEDEN","SATURDAY, APRIL 4, 2009"
78,THE LANDMARK FORT HARRISON FULLY RESTORED,"CLEARWATER, FLORIDA","SATURDAY, MARCH 14, 2009"
79,SCIENTOLOGY OPENS PROMINENT NEW CHURCH IN BERLIN,"BERLIN, GERMANY","SATURDAY, JANUARY 13, 2007"
80,SPECTACULAR GRAND OPENING OF THE CHURCH OF SCI...,"LONDON, ENGLAND","SUNDAY, OCTOBER 22, 2006"
81,CHURCH OF SCIENTOLOGY OF NEW YORK INAUGURATES ...,"NEW YORK, NEW YORK","SUNDAY, SEPTEMBER 26, 2004"
82,THE NATIONAL CHURCH OF SCIENTOLOGY OPENED IN T...,"MADRID, SPAIN","SATURDAY, SEPTEMBER 18, 2004"
83,ORIGINAL TRANSAMERICA BUILDING IS RESTORED AS ...,"SAN FRANCISCO, CALIFORNIA","SATURDAY, NOVEMBER 29, 2003"
84,CHURCH OF SCIENTOLOGY OF JOHANNESBURG OPENS TH...,"JOHANNESBURG, SOUTH AFRICA","SATURDAY, NOVEMBER 1, 2003"

### **Step 7:** Had to clean the data for certain states and cities written without their country or state**

In [165]:
df.loc[df["location"] == "LOS ANGELES", "location"] = "LOS ANGELES, CALIFORNIA"

In [166]:
df[df["location"] == "LOS ANGELES, CALIFORNIA"]

,title,location,date
36,SCIENTOLOGY MEDIA PRODUCTIONS LAUNCHES IN HOLL...,"LOS ANGELES, CALIFORNIA","SATURDAY, MAY 28, 2016"
41,CHURCH OF SCIENTOLOGY MISSION OPENS DOORS TO N...,"LOS ANGELES, CALIFORNIA","SUNDAY, AUGUST 25, 2013"
63,SCIENTOLOGY OPENS RECORD NUMBER OF NEW CHURCHE...,"LOS ANGELES, CALIFORNIA","THURSDAY, JANUARY 27, 2011"
64,"CHURCH OF SCIENTOLOGY FLIPS THE SWITCH ON 185,...","LOS ANGELES, CALIFORNIA","WEDNESDAY, JANUARY 26, 2011"
68,CHURCH OF SCIENTOLOGY OF LOS ANGELES OPENS NEW...,"LOS ANGELES, CALIFORNIA","SATURDAY, APRIL 24, 2010"

In [167]:
df.loc[df["location"] == "GREATER CINCINNATI", "location"] = "GREATER CINCINNATI, OHIO"

In [168]:
df[df["location"] == "GREATER CINCINNATI, OHIO"]

,title,location,date
54,SCIENTOLOGY CHURCH OPENS DOORS TO A TRI-STATE ...,"GREATER CINCINNATI, OHIO","SATURDAY, FEBRUARY 25, 2012"

In [ ]:
#^ran the above lines of code for LA and Greater Cincinatti b/c the website only had the city names alone, not attached to a state.

### **Step 8:** Create a code to separate states/cities/regionsfrom their country so they don't appear as countries themselves.

In [169]:
#country / international chart code for datawrapper. Need to separate US states from USA as country for different charts. 

#when I ran my code and put it into datawrapper it showed certain locations such as LA, Greater
#^Cincinatti, Western Australia, etc. as countries rather than locations in a country which is why I went back and altered it manually/created these lists. 

us_states = [ #all caps like in HTML.
    "CALIFORNIA", "FLORIDA", "TEXAS", "NEW YORK", "ARIZONA",
    "COLORADO", "WASHINGTON", "NEVADA", "ILLINOIS", "UTAH",
    "MISSOURI", "MICHIGAN", "LOUISIANA", "OREGON", "MINNESOTA",
    "TENNESSEE", "GEORGIA", "OHIO", "PUERTO RICO","DC", "D.C."
]

region_map = {
    "WESTERN AUSTRALIA": "AUSTRALIA",
    "ONTARIO": "CANADA",
    "GAUTENG": "SOUTH AFRICA",
    "GREATER CINCINNATI": "USA",
    "LOS ANGELES": "USA"
}

countries = []

for loc in df["location"]:
    loc_upper = str(loc).upper()

    # 1. USA detection for states
    is_us = any(state in loc_upper for state in us_states)

    if is_us:
        countries.append("USA")

    else:
        # 2. If format is "City, Country/Region"
        if ", " in loc_upper:
            last_part = loc_upper.split(", ")[-1].strip()

            # fix known provinces/regions
            if last_part in region_map:
                countries.append(region_map[last_part])
            else:
                countries.append(last_part)

        # 3. 
        else:
            countries.append(loc_upper)

df["country"] = countries

In [170]:
df[df["country"] == "USA"]

,title,location,date,country
0,NEW WATERFRONT RELIGIOUS RETREAT OPENS AT SCIE...,"CLEARWATER, FLORIDA","SATURDAY, APRIL 25, 2026",USA
1,CARIBBEAN CALLING: PUERTO RICAN PRIDE SHINES W...,"SAN JUAN, PUERTO RICO","SUNDAY, FEBRUARY 22, 2026",USA
4,BIG NEWS IN THE CITY OF BIG SHOULDERS AS SCIEN...,"CHICAGO, ILLINOIS","SUNDAY, MARCH 3, 2024",USA
6,NEW SCIENTOLOGY STAR RISES IN TEXAS’SALL-STARC...,"AUSTIN, TEXAS","SATURDAY, FEBRUARY 24, 2024",USA
9,SCIENTOLOGY IDEAL ORG RISES LIKE A LEGENDARY K...,"VENTURA, CALIFORNIA","SATURDAY, FEBRUARY 22, 2020",USA
10,O-H-I-O: NEW CHURCH OF SCIENTOLOGY KICKS OFF I...,"COLUMBUS, CENTRAL OHIO","SATURDAY, NOVEMBER 9, 2019",USA
11,A NEW HOME IN THE HEARTLAND: CHURCH OF SCIENTO...,"KANSAS CITY, MISSOURI","SATURDAY, NOVEMBER 2, 2019",USA
13,MADE IN DETROIT: NEW CHURCH OF SCIENTOLOGY NOW...,"DETROIT, MICHIGAN","SUNDAY, OCTOBER 14, 2018",USA
16,A STAR BURSTS IN “THE CITY BEAUTIFUL” AS A RIB...,"ORLANDO, FLORIDA","SATURDAY, MAY 12, 2018",USA
18,WHERE SPIRITUALITY INTERSECTS WITH HUMAN BRILL...,"SILICON VALLEY, CALIFORNIA","SUNDAY, FEBRUARY 18, 2018",USA
19,"IN THE SPIRIT OF ITS HISTORIC PIONEERS, CITY O...","SALT LAKE CITY, UTAH","SATURDAY, FEBRUARY 17, 2018",USA
24,CELEBRATING 30 YEARS OF SERVICE TO BATON ROUGE...,"BATON ROUGE, LOUISIANA","SATURDAY, JULY 8, 2017",USA
26,A MAGICAL WELCOME GREETS MIAMI’S NEW CHURCH OF...,"MIAMI, FLORIDA","SATURDAY, APRIL 29, 2017",USA
27,NORTH AMERICA’S LARGEST CHURCH OF SCIENTOLOGY ...,"SAN FERNANDO VALLEY, CALIFORNIA","SUNDAY, MARCH 19, 2017",USA
29,CALIFORNIA DREAMING BECOMES REALITY AS SAN DIE...,"SAN DIEGO, CALIFORNIA","SATURDAY, NOVEMBER 19, 2016",USA
30,CHURCH OF SCIENTOLOGY OPENS DOORS TO NEW IDEAL...,"LAKE FOREST, CALIFORNIA","SUNDAY, OCTOBER 23, 2016",USA
33,A NEW ROSE BLOOMS: IDEAL ORG AND COMMUNITY CEN...,"HARLEM, NEW YORK","SUNDAY, JULY 31, 2016",USA
35,CHURCH TRANSFORMS TWO CLEARWATER BUILDINGS INT...,"CLEARWATER, FLORIDA","SATURDAY, JUNE 25, 2016",USA
36,SCIENTOLOGY MEDIA PRODUCTIONS LAUNCHES IN HOLL...,"LOS ANGELES, CALIFORNIA","SATURDAY, MAY 28, 2016",USA
37,ATLANTA’S SPIRIT OF FREEDOM SHINES BRIGHT AS G...,"ATLANTA, GEORGIA","SATURDAY, APRIL 2, 2016",USA
38,CHURCH OF SCIENTOLOGY DEDICATES LANDMARK BUILD...,"CLEARWATER, FLORIDA","SUNDAY, JUNE 29, 2014",USA
41,CHURCH OF SCIENTOLOGY MISSION OPENS DOORS TO N...,"LOS ANGELES, CALIFORNIA","SUNDAY, AUGUST 25, 2013",USA
42,NEW IDEAL CHURCH OF SCIENTOLOGY BLOOMS IN THE ...,"PORTLAND, OREGON","SATURDAY, MAY 11, 2013",USA
46,CHURCH OF SCIENTOLOGY OPENS NATIONAL OFFICE IN...,"WASHINGTON, D.C.","WEDNESDAY, SEPTEMBER 12, 2012",USA
48,BAY AREA SCIENTOLOGISTS REDEDICATE IDEAL CHURC...,"LOS GATOS, CALIFORNIA","SATURDAY, JULY 28, 2012",USA
49,SCIENTOLOGISTS CUT THE RIBBON ON LANDMARK BUFF...,"BUFFALO, NEW YORK","SATURDAY, JUNE 30, 2012",USA
50,RIBBON FALLS ON IDEAL ORG IN THE BIRTHPLACE OF...,"PHOENIX, ARIZONA","SATURDAY, JUNE 23, 2012",USA
51,NEW IDEAL CHURCH OF SCIENTOLOGY FOR THE MILE-H...,"DENVER, COLORADO","SATURDAY, JUNE 16, 2012",USA
52,SCIENTOLOGY REBOOTS IDEAL CHURCH IN SILICON VA...,"SAN JOSE, CALIFORNIA","SATURDAY, JUNE 9, 2012",USA
53,ORANGE COUNTY WELCOMES CHURCH OF SCIENTOLOGY T...,"SANTA ANA, CALIFORNIA","SATURDAY, JUNE 2, 2012",USA
54,SCIENTOLOGY CHURCH OPENS DOORS TO A TRI-STATE ...,"GREATER CINCINNATI, OHIO","SATURDAY, FEBRUARY 25, 2012",USA
55,CHURCH OF SCIENTOLOGY INAUGURATES NEW LANDMARK...,"SACRAMENTO, CALIFORNIA","SATURDAY, JANUARY 28, 2012",USA
57,CHURCH OF SCIENTOLOGY INGLEWOOD—VIDEO FOOTAGE ...,"INGLEWOOD, CALIFORNIA","SATURDAY, NOVEMBER 5, 2011",USA
58,CHURCH OF SCIENTOLOGY CELEBRATES THE OPENING O...,"INGLEWOOD, CALIFORNIA","SATURDAY, NOVEMBER 5, 2011",USA
59,CHURCH OF SCIENTOLOGY CUTS RIBBON ON TWIN CITI...,"ST. PAUL, MINNESOTA","SATURDAY, OCTOBER 22, 2011",USA
60,JOHN TRAVOLTA OPENS CHURCH OF SCIENTOLOGY MISS...,"OCALA, FLORIDA, USA","SUNDAY, MAY 29, 2011",USA
61,CHURCH OF SCIENTOLOGY OF TAMPA EXPANDS INTO NE...,"TAMPA, FLORIDA","SUNDAY, MARCH 13, 2011",USA
63,SCIENTOLOGY OPENS RECORD NUMBER OF NEW CHURCHE...,"LOS ANGELES, CALIFORNIA","THURSDAY, JANUARY 27, 2011",USA
64,"CHURCH OF SCIENTOLOGY FLIPS THE SWITCH ON 185,...","LOS ANGELES, CALIFORNIA","WEDNESDAY, JANUARY 26, 2011",USA
65,CHURCH OF SCIENTOLOGY DEDICATES NEW BUILDING F...,"SEATTLE, WASHINGTON","SATURDAY, JULY 24, 2010",USA
66,"NEW IDEAL SCIENTOLOGY CHURCH IN PASADENA, CALI...","PASADENA, CALIFORNIA","SUNDAY, JULY 18, 2010",USA
68,CHURCH OF SCIENTOLOGY OF LOS ANGELES OPENS NEW...,"LOS ANGELES, CALIFORNIA","SATURDAY, APRIL 24, 2010",USA
70,"NEW 40,000-SQUARE-FOOT CHURCH OF SCIENTOLOGY O...","LAS VEGAS, NEVADA","SATURDAY, FEBRUARY 6, 2010",USA
73,FOUNDING CHURCH OF SCIENTOLOGY GRAND OPENING I...,"WASHINGTON, DC","SATURDAY, OCTOBER 31, 2009",USA
75,CHURCH OF SCIENTOLOGY OPENS NEW CELEBRITY CENT...,"NASHVILLE, TENNESSEE","SATURDAY, APRIL 25, 2009",USA
76,SCIENTOLOGY OPENS NEW CHURCH IN DALLAS,"DALLAS, TEXAS","SATURDAY, APRIL 11, 2009",USA
78,THE LANDMARK FORT HARRISON FULLY RESTORED,"CLEARWATER, FLORIDA","SATURDAY, MARCH 14, 2009",USA
81,CHURCH OF SCIENTOLOGY OF NEW YORK INAUGURATES ...,"NEW YORK, NEW YORK","SUNDAY, SEPTEMBER 26, 2004",USA
83,ORIGINAL TRANSAMERICA BUILDING IS RESTORED AS ...,"SAN FRANCISCO, CALIFORNIA","SATURDAY, NOVEMBER 29, 2003",USA

In [171]:
df['country'] = countries

In [172]:
len(df[df["country"] == "USA"])

49

In [173]:
df.shape

(85, 4)

### **Step 9:** Create a column for openings per year

In [174]:
#create a year column:

df["year"] = df["date"].str.extract(r"(\d{4})") #used regex  

#create chart data for datawrapper - show openings per year from 2003 - 2026: 

year_df = df.groupby("year").size().reset_index(name="openings") #reset_index makes new column/df & .size() counts rows in groups.

year_df #displays table w/ above work done.

    year  openings
0   2003         2
1   2004         2
2   2006         1
3   2007         1
4   2009         6
5   2010         8
6   2011         8
7   2012        12
8   2013         5
9   2014         2
10  2016         9
11  2017         8
12  2018         8
13  2019         3
14  2020         1
15  2023         2
16  2024         4
17  2025         1
18  2026         2

### **Step 10:** Find the total number of grand openings per country in the archive

In [175]:
country_df = df["country"].value_counts().reset_index()
country_df.columns = ["country", "count"]

country_df

         country  count
0            USA     49
1   SOUTH AFRICA      6
2          ITALY      4
3      AUSTRALIA      4
4        ENGLAND      3
5        GERMANY      3
6         MEXICO      2
7        DENMARK      2
8         CANADA      2
9         FRANCE      1
10      SLOVAKIA      1
11   NEW ZEALAND      1
12       IRELAND      1
13       HUNGARY      1
14        TAIWAN      1
15        ISRAEL      1
16       BELGIUM      1
17        SWEDEN      1
18         SPAIN      1

In [176]:
df.columns

Index(['title', 'location', 'date', 'country', 'year'], dtype='str')

### **Step 11:** Optional: order countries alphabetically

In [177]:
sorted(df["country"].unique())

['AUSTRALIA',
 'BELGIUM',
 'CANADA',
 'DENMARK',
 'ENGLAND',
 'FRANCE',
 'GERMANY',
 'HUNGARY',
 'IRELAND',
 'ISRAEL',
 'ITALY',
 'MEXICO',
 'NEW ZEALAND',
 'SLOVAKIA',
 'SOUTH AFRICA',
 'SPAIN',
 'SWEDEN',
 'TAIWAN',
 'USA']

In [180]:
locations = doc.find_all("span", class_="location-color")

for loc in locations:
    print(loc.get_text(strip=True))

### **Step 12:** Sort US states to see the number of grand openings in each

In [183]:
#need to separate US states from the country list and have info for state chart since most concentrated in USA.

us_rows = []

for loc in df["location"]:
    loc_upper = str(loc).upper()

    for state in us_states:
        if state in loc_upper:
            us_rows.append(state)

state_df = pd.Series(us_rows).value_counts().reset_index()
state_df.columns = ["state", "count"]

state_df

          state  count
0    CALIFORNIA     18
1       FLORIDA      8
2      NEW YORK      3
3    WASHINGTON      3
4         TEXAS      2
5          OHIO      2
6   PUERTO RICO      1
7      ILLINOIS      1
8      MISSOURI      1
9      MICHIGAN      1
10         UTAH      1
11    LOUISIANA      1
12      GEORGIA      1
13       OREGON      1
14         D.C.      1
15      ARIZONA      1
16     COLORADO      1
17    MINNESOTA      1
18       NEVADA      1
19           DC      1
20    TENNESSEE      1

In [185]:
state_df["state"].head(20)

0      CALIFORNIA
1         FLORIDA
2        NEW YORK
3      WASHINGTON
4           TEXAS
5            OHIO
6     PUERTO RICO
7        ILLINOIS
8        MISSOURI
9        MICHIGAN
10           UTAH
11      LOUISIANA
12        GEORGIA
13         OREGON
14           D.C.
15        ARIZONA
16       COLORADO
17      MINNESOTA
18         NEVADA
19             DC
Name: state, dtype: str

In [186]:
df.shape

(85, 5)

In [188]:
df.head(80) #wanted to check df again

,title,location,date,country,year
0,NEW WATERFRONT RELIGIOUS RETREAT OPENS AT SCIE...,"CLEARWATER, FLORIDA","SATURDAY, APRIL 25, 2026",USA,2026
1,CARIBBEAN CALLING: PUERTO RICAN PRIDE SHINES W...,"SAN JUAN, PUERTO RICO","SUNDAY, FEBRUARY 22, 2026",USA,2026
2,TEN STORIES OF TRIUMPH FOR SOUTH AFRICA AS NEW...,"GQEBERHA, EASTERN CAPE, SOUTH AFRICA","SUNDAY, APRIL 6, 2025",SOUTH AFRICA,2025
3,DAZZLING NEW SCIENTOLOGY IDEAL ORG SHINES BRIG...,"PARIS, FRANCE","SATURDAY, APRIL 6, 2024",FRANCE,2024
4,BIG NEWS IN THE CITY OF BIG SHOULDERS AS SCIEN...,"CHICAGO, ILLINOIS","SUNDAY, MARCH 3, 2024",USA,2024
5,MEXICO CITY’S NIGHT SKY LIGHTS UP WITH OPENING...,"MEXICO CITY, MEXICO","FRIDAY, MARCH 1, 2024",MEXICO,2024
6,NEW SCIENTOLOGY STAR RISES IN TEXAS’SALL-STARC...,"AUSTIN, TEXAS","SATURDAY, FEBRUARY 24, 2024",USA,2024
7,CHURCH OF SCIENTOLOGY ANSWERS ONGOING EUROPEAN...,"COPENHAGEN, DENMARK","SUNDAY, NOVEMBER 12, 2023",DENMARK,2023
8,IGNITING A NEW ERA OF EXPANSION FOR SCIENTOLOG...,"EAST GRINSTEAD, ENGLAND","SUNDAY, NOVEMBER 5, 2023",ENGLAND,2023
9,SCIENTOLOGY IDEAL ORG RISES LIKE A LEGENDARY K...,"VENTURA, CALIFORNIA","SATURDAY, FEBRUARY 22, 2020",USA,2020
10,O-H-I-O: NEW CHURCH OF SCIENTOLOGY KICKS OFF I...,"COLUMBUS, CENTRAL OHIO","SATURDAY, NOVEMBER 9, 2019",USA,2019
11,A NEW HOME IN THE HEARTLAND: CHURCH OF SCIENTO...,"KANSAS CITY, MISSOURI","SATURDAY, NOVEMBER 2, 2019",USA,2019
12,WINDS OF CHANGE: SCIENTOLOGY HEADQUARTERS FOR ...,"JOHANNESBURG, SOUTH AFRICA","TUESDAY, JANUARY 1, 2019",SOUTH AFRICA,2019
13,MADE IN DETROIT: NEW CHURCH OF SCIENTOLOGY NOW...,"DETROIT, MICHIGAN","SUNDAY, OCTOBER 14, 2018",USA,2018
14,NEW SCIENTOLOGY MISSION OF COMO GRACES NORTHER...,"COMO, ITALY","SUNDAY, SEPTEMBER 30, 2018",ITALY,2018
15,FREEDOM REIGNS AS THE CHURCH OF SCIENTOLOGY ST...,"STUTTGART, GERMANY","SUNDAY, SEPTEMBER 9, 2018",GERMANY,2018
16,A STAR BURSTS IN “THE CITY BEAUTIFUL” AS A RIB...,"ORLANDO, FLORIDA","SATURDAY, MAY 12, 2018",USA,2018
17,DOWN UNDER’S “CITY OF LIGHTS” WELCOMES NEWEST ...,"PERTH, WESTERN AUSTRALIA","SATURDAY, MAY 5, 2018",AUSTRALIA,2018
18,WHERE SPIRITUALITY INTERSECTS WITH HUMAN BRILL...,"SILICON VALLEY, CALIFORNIA","SUNDAY, FEBRUARY 18, 2018",USA,2018
19,"IN THE SPIRIT OF ITS HISTORIC PIONEERS, CITY O...","SALT LAKE CITY, UTAH","SATURDAY, FEBRUARY 17, 2018",USA,2018
20,SCIENTOLOGY OPENS DOORS TO NEW IDEAL MISSION I...,"KOŠICE, SLOVAKIA","SATURDAY, JANUARY 13, 2018",SLOVAKIA,2018
21,FESTIVE SPIRIT: JOHANNESBURG WELCOMES NEW CHUR...,"JOBURG NORTH, SOUTH AFRICA","SATURDAY, DECEMBER 23, 2017",SOUTH AFRICA,2017
22,A REVOLUTION OF THE SPIRIT IN BRITAIN’S SALT O...,"BIRMINGHAM, ENGLAND","SATURDAY, OCTOBER 21, 2017",ENGLAND,2017
23,DEDICATING THE NEW IDEAL MISSION OF SCIENTOLOG...,"SENIGALLIA, ITALY","THURSDAY, SEPTEMBER 28, 2017",ITALY,2017
24,CELEBRATING 30 YEARS OF SERVICE TO BATON ROUGE...,"BATON ROUGE, LOUISIANA","SATURDAY, JULY 8, 2017",USA,2017
25,DANISH DELIGHT: A NEW CHURCH OF SCIENTOLOGY IS...,"COPENHAGEN, DENMARK","SATURDAY, MAY 27, 2017",DENMARK,2017
26,A MAGICAL WELCOME GREETS MIAMI’S NEW CHURCH OF...,"MIAMI, FLORIDA","SATURDAY, APRIL 29, 2017",USA,2017
27,NORTH AMERICA’S LARGEST CHURCH OF SCIENTOLOGY ...,"SAN FERNANDO VALLEY, CALIFORNIA","SUNDAY, MARCH 19, 2017",USA,2017
28,A TREASURED LANDMARK REBORN—SCIENTOLOGY OPENS ...,"AUCKLAND, NEW ZEALAND","SATURDAY, JANUARY 21, 2017",NEW ZEALAND,2017
29,CALIFORNIA DREAMING BECOMES REALITY AS SAN DIE...,"SAN DIEGO, CALIFORNIA","SATURDAY, NOVEMBER 19, 2016",USA,2016
30,CHURCH OF SCIENTOLOGY OPENS DOORS TO NEW IDEAL...,"LAKE FOREST, CALIFORNIA","SUNDAY, OCTOBER 23, 2016",USA,2016
31,CHURCH OF SCIENTOLOGY CUTS A RIBBON ON NATIONA...,"DUBLIN, IRELAND","SATURDAY, OCTOBER 15, 2016",IRELAND,2016
32,SCIENTOLOGY CROWNS RECORD GROWTH WITH ALL-NEW ...,"SYDNEY, AUSTRALIA","SUNDAY, SEPTEMBER 4, 2016",AUSTRALIA,2016
33,A NEW ROSE BLOOMS: IDEAL ORG AND COMMUNITY CEN...,"HARLEM, NEW YORK","SUNDAY, JULY 31, 2016",USA,2016
34,A SAGA OF FREEDOM CULMINATES IN IDEAL CHURCH C...,"BUDAPEST, HUNGARY","SATURDAY, JULY 23, 2016",HUNGARY,2016
35,CHURCH TRANSFORMS TWO CLEARWATER BUILDINGS INT...,"CLEARWATER, FLORIDA","SATURDAY, JUNE 25, 2016",USA,2016
36,SCIENTOLOGY MEDIA PRODUCTIONS LAUNCHES IN HOLL...,"LOS ANGELES, CALIFORNIA","SATURDAY, MAY 28, 2016",USA,2016
37,ATLANTA’S SPIRIT OF FREEDOM SHINES BRIGHT AS G...,"ATLANTA, GEORGIA","SATURDAY, APRIL 2, 2016",USA,2016
38,CHURCH OF SCIENTOLOGY DEDICATES LANDMARK BUILD...,"CLEARWATER, FLORIDA","SUNDAY, JUNE 29, 2014",USA,2014
39,NEW IDEAL ORG IN THE HEART OF AUSTRALIA’S HARB...,"SYDNEY, AUSTRALIA","SATURDAY, MAY 3, 2014",AUSTRALIA,2014
40,AN IDEAL ORG AT THE GATEWAY OF THE CHINESE-SPE...,"KAOHSIUNG, TAIWAN","SATURDAY, DECEMBER 7, 2013",TAIWAN,2013
41,CHURCH OF SCIENTOLOGY MISSION OPENS DOORS TO N...,"LOS ANGELES, CALIFORNIA","SUNDAY, AUGUST 25, 2013",USA,2013
42,NEW IDEAL CHURCH OF SCIENTOLOGY BLOOMS IN THE ...,"PORTLAND, OREGON","SATURDAY, MAY 11, 2013",USA,2013
43,SOUTH AFRICAN CAPITAL HERALDS NEW CHURCH OF SC...,"PRETORIA, GAUTENG","SATURDAY, FEBRUARY 23, 2013",SOUTH AFRICA,2013
44,CHURCH OF SCIENTOLOGY CUTS RIBBON ON NEW IDEAL...,"CAMBRIDGE, ONTARIO","SATURDAY, FEBRUARY 9, 2013",CANADA,2013
45,THOUSANDS CELEBRATE NEW SCIENTOLOGY CHURCH IN ...,"PADUA, ITALY","SATURDAY, OCTOBER 27, 2012",ITALY,2012
46,CHURCH OF SCIENTOLOGY OPENS NATIONAL OFFICE IN...,"WASHINGTON, D.C.","WEDNESDAY, SEPTEMBER 12, 2012",USA,2012
47,RIBBON FALLS ON IDEAL CENTER OF SCIENTOLOGY FO...,"TEL AVIV, ISRAEL","TUESDAY, AUGUST 21, 2012",ISRAEL,2012
48,BAY AREA SCIENTOLOGISTS REDEDICATE IDEAL CHURC...,"LOS GATOS, CALIFORNIA","SATURDAY, JULY 28, 2012",USA,2012
49,SCIENTOLOGISTS CUT THE RIBBON ON LANDMARK BUFF...,"BUFFALO, NEW YORK","SATURDAY, JUNE 30, 2012",USA,2012
50,RIBBON FALLS ON IDEAL ORG IN THE BIRTHPLACE OF...,"PHOENIX, ARIZONA","SATURDAY, JUNE 23, 2012",USA,2012
51,NEW IDEAL CHURCH OF SCIENTOLOGY FOR THE MILE-H...,"DENVER, COLORADO","SATURDAY, JUNE 16, 2012",USA,2012
52,SCIENTOLOGY REBOOTS IDEAL CHURCH IN SILICON VA...,"SAN JOSE, CALIFORNIA","SATURDAY, JUNE 9, 2012",USA,2012
53,ORANGE COUNTY WELCOMES CHURCH OF SCIENTOLOGY T...,"SANTA ANA, CALIFORNIA","SATURDAY, JUNE 2, 2012",USA,2012
54,SCIENTOLOGY CHURCH OPENS DOORS TO A TRI-STATE ...,"GREATER CINCINNATI, OHIO","SATURDAY, FEBRUARY 25, 2012",USA,2012
55,CHURCH OF SCIENTOLOGY INAUGURATES NEW LANDMARK...,"SACRAMENTO, CALIFORNIA","SATURDAY, JANUARY 28, 2012",USA,2012
56,HAMBURG DEDICATES A NEW IDEAL CHURCH OF SCIENT...,"HAMBURG, GERMANY","SATURDAY, JANUARY 21, 2012",GERMANY,2012
57,CHURCH OF SCIENTOLOGY INGLEWOOD—VIDEO FOOTAGE ...,"INGLEWOOD, CALIFORNIA","SATURDAY, NOVEMBER 5, 2011",USA,2011
58,CHURCH OF SCIENTOLOGY CELEBRATES THE OPENING O...,"INGLEWOOD, CALIFORNIA","SATURDAY, NOVEMBER 5, 2011",USA,2011
59,CHURCH OF SCIENTOLOGY CUTS RIBBON ON TWIN CITI...,"ST. PAUL, MINNESOTA","SATURDAY, OCTOBER 22, 2011",USA,2011
60,JOHN TRAVOLTA OPENS CHURCH OF SCIENTOLOGY MISS...,"OCALA, FLORIDA, USA","SUNDAY, MAY 29, 2011",USA,2011
61,CHURCH OF SCIENTOLOGY OF TAMPA EXPANDS INTO NE...,"TAMPA, FLORIDA","SUNDAY, MARCH 13, 2011",USA,2011
62,RIBBON FALLS ON AUSTRALIA’S FIRST IDEAL CHURCH...,"MELBOURNE, AUSTRALIA","SATURDAY, JANUARY 29, 2011",AUSTRALIA,2011
63,SCIENTOLOGY OPENS RECORD NUMBER OF NEW CHURCHE...,"LOS ANGELES, CALIFORNIA","THURSDAY, JANUARY 27, 2011",USA,2011
64,"CHURCH OF SCIENTOLOGY FLIPS THE SWITCH ON 185,...","LOS ANGELES, CALIFORNIA","WEDNESDAY, JANUARY 26, 2011",USA,2011
65,CHURCH OF SCIENTOLOGY DEDICATES NEW BUILDING F...,"SEATTLE, WASHINGTON","SATURDAY, JULY 24, 2010",USA,2010
66,"NEW IDEAL SCIENTOLOGY CHURCH IN PASADENA, CALI...","PASADENA, CALIFORNIA","SUNDAY, JULY 18, 2010",USA,2010
67,SCIENTOLOGY OPENS NEW NATIONAL ORGANIZATION FO...,"MEXICO CITY, MEXICO","SATURDAY, JULY 10, 2010",MEXICO,2010
68,CHURCH OF SCIENTOLOGY OF LOS ANGELES OPENS NEW...,"LOS ANGELES, CALIFORNIA","SATURDAY, APRIL 24, 2010",USA,2010
69,SCIENTOLOGY LIFE IMPROVEMENT CENTRE OPENS IN J...,"JOHANNESBURG, SOUTH AFRICA","FRIDAY, MARCH 26, 2010",SOUTH AFRICA,2010
70,"NEW 40,000-SQUARE-FOOT CHURCH OF SCIENTOLOGY O...","LAS VEGAS, NEVADA","SATURDAY, FEBRUARY 6, 2010",USA,2010
71,NEW CHURCH IN THE HISTORIC HEART OF FRENCH CANADA,"QUÉBEC, CANADA","SATURDAY, JANUARY 30, 2010",CANADA,2010
72,NEW BRANCH OF CHURCHES OF SCIENTOLOGY FOR EURO...,"BRUSSELS, BELGIUM","SATURDAY, JANUARY 23, 2010",BELGIUM,2010
73,FOUNDING CHURCH OF SCIENTOLOGY GRAND OPENING I...,"WASHINGTON, DC","SATURDAY, OCTOBER 31, 2009",USA,2009
74,NEW CHURCH OF SCIENTOLOGY OPENS DOORS TO ROME,"ROME, ITALY","SATURDAY, OCTOBER 24, 2009",ITALY,2009
75,CHURCH OF SCIENTOLOGY OPENS NEW CELEBRITY CENT...,"NASHVILLE, TENNESSEE","SATURDAY, APRIL 25, 2009",USA,2009
76,SCIENTOLOGY OPENS NEW CHURCH IN DALLAS,"DALLAS, TEXAS","SATURDAY, APRIL 11, 2009",USA,2009
77,THE KNOWLEDGE CENTER OF NORTHERN EUROPE,"MALMÖ, SWEDEN","SATURDAY, APRIL 4, 2009",SWEDEN,2009
78,THE LANDMARK FORT HARRISON FULLY RESTORED,"CLEARWATER, FLORIDA","SATURDAY, MARCH 14, 2009",USA,2009
79,SCIENTOLOGY OPENS PROMINENT NEW CHURCH IN BERLIN,"BERLIN, GERMANY","SATURDAY, JANUARY 13, 2007",GERMANY,2007

### **Step 13:** Group the openings for each country per year into 3 time periods for datawrapper chart

In [190]:
#below groups it into the time periods I assign:
#need to make year an int not str
df["year"] = df["year"].astype(int)

def get_period(year):
    if 2003 <= year <= 2009:
        return "2003–2009"
    elif 2010 <= year <= 2016:
        return "2010–2016"
    elif 2017 <= year <= 2026:
        return "2017–2026"
    else:
        return None

#below makes new column before making pivot table for time periods above 
df["period"] = df["year"].apply(get_period)

In [191]:
#google / TA said to do pivot table 
table = df.pivot_table(
    index="country",
    columns="period",
    values="title",
    aggfunc="count",
    fill_value=0
)

table

period        2003–2009  2010–2016  2017–2026
country
AUSTRALIA             0          3          1
BELGIUM               0          1          0
CANADA                0          2          0
DENMARK               0          0          2
ENGLAND               1          0          2
FRANCE                0          0          1
GERMANY               1          1          1
HUNGARY               0          1          0
IRELAND               0          1          0
ISRAEL                0          1          0
ITALY                 1          1          2
MEXICO                0          1          1
NEW ZEALAND           0          0          1
SLOVAKIA              0          0          1
SOUTH AFRICA          1          2          3
SPAIN                 1          0          0
SWEDEN                1          0          0
TAIWAN                0          1          0
USA                   6         29         14

### **Step 14:** Save all of the df's into CSV files.

In [194]:
df.to_csv("scientology_openings.csv", index=False)
year_df.to_csv("year_chart.csv", index=False)
country_df.to_csv("international_locations.csv", index=False)
state_df.to_csv("us_states.csv", index=False)
df.to_csv("scientology_map.csv", index=False)

In [113]:
df.tail() #extra check again to ensure # of locations

,title,location,date,country,year,period
80,SPECTACULAR GRAND OPENING OF THE CHURCH OF SCI...,"LONDON, ENGLAND","SUNDAY, OCTOBER 22, 2006",ENGLAND,2006,2003–2009
81,CHURCH OF SCIENTOLOGY OF NEW YORK INAUGURATES ...,"NEW YORK, NEW YORK","SUNDAY, SEPTEMBER 26, 2004",USA,2004,2003–2009
82,THE NATIONAL CHURCH OF SCIENTOLOGY OPENED IN T...,"MADRID, SPAIN","SATURDAY, SEPTEMBER 18, 2004",SPAIN,2004,2003–2009
83,ORIGINAL TRANSAMERICA BUILDING IS RESTORED AS ...,"SAN FRANCISCO, CALIFORNIA","SATURDAY, NOVEMBER 29, 2003",USA,2003,2003–2009
84,CHURCH OF SCIENTOLOGY OF JOHANNESBURG OPENS TH...,"JOHANNESBURG, SOUTH AFRICA","SATURDAY, NOVEMBER 1, 2003",SOUTH AFRICA,2003,2003–2009